---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ${ELASTICSEARCH_HOST:127.0.0.1}
  port: ${ELASTICSEARCH_PORT:9200}
  url_prefix:
  use_ssl: ${SSL_ENABLED:False}
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth: ${ELASTICSEARCH_USER_PASS:}
  timeout: 120
  master_only: False

logging:
  loglevel: ${LOG_LEVEL:INFO}
  logfile: 
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
